builds:
  - binary: godlp
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: godlp
    formula: Formula
    homepage: https://github.com/mcreekmore/godlp
    description: 'A convenient wrapper for yt-dlp'
    repository:
      owner: mcreekmore
      name: homebrew-mcreekmore
    commit_author:
      name: mcreekmore
      email: matthewacreekmore@gmail.com

checksum:
  name_template: 'checksums.txt'
